import { CONFIG } from './modules/config.js';
import { History } from './modules/history.js';
import { applyHalftone } from './modules/halftone.js';
import { vectorize } from './modules/vector.js';
import { cloneImageData, downloadBlob, fileToImage, fitCanvasSize, imageDataToCanvas, canvasToBlob, resizeCanvas } from './modules/utils.js';
import { removeBackground, aiUpscale } from './modules/ai.js';

const $ = id => document.getElementById(id);
const canvas = $('canvas'), ctx = canvas.getContext('2d', { willReadFrequently: true });
const compareCanvas = $('compareCanvas'), compareCtx = compareCanvas.getContext('2d');
const history = new History(20);
let originalData = null, originalName = 'SZAS', lastSvg = '', zoom = 1, compareOn = false, processing = false;
let settings = { brightness: 0, contrast: 0, saturation: 0, sharpness: 0 }, adjustBase = null;
let half = { dot: 6, contrast: 50, density: 100, angle: 45, pattern: 'circle', invert: false };

function toast(message) { const host = $('toastHost'), el = document.createElement('div'); el.className = 'toast'; el.textContent = message; host.appendChild(el); requestAnimationFrame(() => el.classList.add('show')); setTimeout(() => { el.classList.remove('show'); setTimeout(() => el.remove(), 250); }, 1900); }
function busy(show, title = 'PROCESANDO', text = 'Motor local') { processing = show; $('busy').style.display = show ? 'flex' : 'none'; $('busyTitle').textContent = title; $('busyText').textContent = text; }
function requireImage() { if (!originalData) { toast('SUBE UNA IMAGEN PRIMERO'); return false; } return true; }
function currentData() { return cloneImageData(ctx.getImageData(0, 0, canvas.width, canvas.height)); }
function setImageData(im, mode = 'EDITED', shouldFit = true) { canvas.width = im.width; canvas.height = im.height; ctx.putImageData(im, 0, 0); canvas.style.display = 'block'; $('emptyState').style.display = 'none'; $('imageInfo').textContent = `${im.width} × ${im.height} PX`; $('modeInfo').textContent = mode; updatePrint(); if (shouldFit) fit(); }
function commit() { if (canvas.width) history.push(currentData()); }
function fit() { zoom = 1; canvas.style.transform = 'scale(1)'; $('zoomLabel').textContent = '100%'; }
function syncSliders() { ['brightness', 'contrast', 'saturation', 'sharpness'].forEach(k => { $(k).value = settings[k]; $(k + 'Out').textContent = settings[k]; }); }
function renderAdjustments(base) {
  if (!base) return; const im = cloneImageData(base), d = im.data;
  const b = settings.brightness * 2.55, c = settings.contrast, f = (259 * (c + 255)) / (255 * (259 - c)), sat = 1 + settings.saturation / 100;
  for (let i = 0; i < d.length; i += 4) { let r = (d[i] - 128) * f + 128 + b, g = (d[i + 1] - 128) * f + 128 + b, bl = (d[i + 2] - 128) * f + 128 + b; const gray = .299 * r + .587 * g + .114 * bl; r = gray + (r - gray) * sat; g = gray + (g - gray) * sat; bl = gray + (bl - gray) * sat; d[i] = Math.max(0, Math.min(255, r)); d[i + 1] = Math.max(0, Math.min(255, g)); d[i + 2] = Math.max(0, Math.min(255, bl)); }
  setImageData(im, 'ADJUSTED', false); if (settings.sharpness) applySharpen(settings.sharpness / 100); }
function applySharpen(k) { const src = currentData(), out = ctx.createImageData(src.width, src.height), a = src.data, b = out.data, w = src.width, h = src.height, idx = (x, y) => (y * w + x) * 4; for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const p = idx(x, y); for (let c = 0; c < 3; c++) { let v = a[p + c] * (1 + 4 * k); if (x) v -= a[idx(x - 1, y) + c] * k; if (x < w - 1) v -= a[idx(x + 1, y) + c] * k; if (y) v -= a[idx(x, y - 1) + c] * k; if (y < h - 1) v -= a[idx(x, y + 1) + c] * k; b[p + c] = Math.max(0, Math.min(255, v)); } b[p + 3] = a[p + 3]; } ctx.putImageData(out, 0, 0); }
function finishAdjust() { if (!adjustBase) return; commit(); adjustBase = null; }

async function loadFile(file) {
  if (!file) return;
  if (file.size > CONFIG.maxFileBytes) return toast('IMAGEN DEMASIADO GRANDE · MÁX. 20 MB');
  if (!['image/png', 'image/jpeg', 'image/webp'].includes((file.type || '').toLowerCase())) return toast('SOLO PNG / JPG / WEBP');
  try {
    const img = await fileToImage(file); const size = fitCanvasSize(img.naturalWidth, img.naturalHeight, CONFIG.maxCanvasPixels);
    const source = document.createElement('canvas'); source.width = size.width; source.height = size.height; const sc = source.getContext('2d'); sc.imageSmoothingEnabled = true; sc.imageSmoothingQuality = 'high'; sc.drawImage(img, 0, 0, size.width, size.height);
    originalData = cloneImageData(sc.getImageData(0, 0, size.width, size.height)); history.clear(); settings = { brightness: 0, contrast: 0, saturation: 0, sharpness: 0 }; syncSliders(); setImageData(cloneImageData(originalData), 'ORIGINAL'); originalName = (file.name || 'SZAS').replace(/\.[^.]+$/, ''); $('fileName').textContent = (file.name || 'IMAGEN').toUpperCase(); $('fileHealth').textContent = size.scale < 1 ? `REDUCIDA A ${size.width} × ${size.height} PX · LÍMITE DE SEGURIDAD` : `CARGADA · ${Math.round(file.size / 1024)} KB`; $('fileHealth').className = 'file-health ok'; toast('IMAGEN CARGADA');
  } catch (e) { console.error(e); $('fileHealth').textContent = 'ERROR AL LEER LA IMAGEN'; $('fileHealth').className = 'file-health bad'; toast(e.message || 'NO SE PUDO CARGAR'); }
}

function destructiveImageData(transform, mode) { if (!requireImage()) return; finishAdjust(); commit(); const out = transform(currentData()); if (out) setImageData(out, mode); }
function simple(name) { destructiveImageData(im => { const d = im.data; for (let i = 0; i < d.length; i += 4) { if (name === 'grayscale') { const g = .299 * d[i] + .587 * d[i + 1] + .114 * d[i + 2]; d[i] = d[i + 1] = d[i + 2] = g; } else if (name === 'threshold') { const g = (.299 * d[i] + .587 * d[i + 1] + .114 * d[i + 2]) >= 128 ? 255 : 0; d[i] = d[i + 1] = d[i + 2] = g; } else { d[i] = 255 - d[i]; d[i + 1] = 255 - d[i + 1]; d[i + 2] = 255 - d[i + 2]; } } return im; }, name.toUpperCase()); }
function edgeClean() { destructiveImageData(im => { const d = im.data, w = im.width, h = im.height; for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) { const p = (y * w + x) * 4; if (d[p + 3] > 0 && d[p + 3] < 255) { let a = 0; for (let yy = -1; yy <= 1; yy++) for (let xx = -1; xx <= 1; xx++) a += d[((y + yy) * w + x + xx) * 4 + 3]; d[p + 3] = Math.max(d[p + 3], Math.round(a / 9)); } } return im; }, 'EDGE CLEAN'); }
function cutout() { destructiveImageData(im => { const d = im.data; for (let i = 0; i < d.length; i += 4) { const g = .299 * d[i] + .587 * d[i + 1] + .114 * d[i + 2]; d[i + 3] = g >= 128 ? 255 : 0; } return im; }, 'CALADO'); }
function autocrop() { if (!requireImage()) return; finishAdjust(); const im = currentData(), d = im.data, w = im.width, h = im.height; let minX = w, minY = h, maxX = -1, maxY = -1; for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { if (d[(y * w + x) * 4 + 3] > 10) { minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); } } if (maxX < 0) return toast('NO HAY CONTENIDO VISIBLE'); commit(); const out = ctx.getImageData(minX, minY, maxX - minX + 1, maxY - minY + 1); setImageData(out, 'AUTOCROP'); toast('RECORTADO AL CONTENIDO'); }
function resetOriginal() { if (!requireImage()) return; finishAdjust(); commit(); setImageData(cloneImageData(originalData), 'ORIGINAL'); settings = { brightness: 0, contrast: 0, saturation: 0, sharpness: 0 }; syncSliders(); toast('ORIGINAL RESTAURADO'); }
function enhance() { if (!requireImage()) return; finishAdjust(); commit(); const im = currentData(), d = im.data; const contrast = 1.12; for (let i = 0; i < d.length; i += 4) { d[i] = Math.max(0, Math.min(255, (d[i] - 128) * contrast + 128)); d[i + 1] = Math.max(0, Math.min(255, (d[i + 1] - 128) * contrast + 128)); d[i + 2] = Math.max(0, Math.min(255, (d[i + 2] - 128) * contrast + 128)); } setImageData(im, 'ENHANCED'); toast('MEJORA LOCAL APLICADA'); }
function denoise() { if (!requireImage()) return; finishAdjust(); commit(); const src = currentData(), out = new ImageData(src.width, src.height), a = src.data, b = out.data, w = src.width, h = src.height; for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const vals = [[], [], []]; for (let yy = -1; yy <= 1; yy++) for (let xx = -1; xx <= 1; xx++) { const X = Math.max(0, Math.min(w - 1, x + xx)), Y = Math.max(0, Math.min(h - 1, y + yy)), p = (Y * w + X) * 4; for (let c = 0; c < 3; c++) vals[c].push(a[p + c]); } const p = (y * w + x) * 4; for (let c = 0; c < 3; c++) { vals[c].sort((u, v) => u - v); b[p + c] = vals[c][4]; } b[p + 3] = a[p + 3]; } setImageData(out, 'DENOISED'); toast('RUIDO REDUCIDO'); }

async function runAI(kind) { if (!requireImage() || processing) return; finishAdjust(); busy(true, kind === 'remove' ? 'IA / QUITAR FONDO' : 'IA / AMPLIAR 4×', 'La primera vez descarga el modelo al navegador.'); try { let input = imageDataToCanvas(currentData()); if (kind === 'upscale') { const max = CONFIG.maxAIInputSide; const scale = Math.min(1, max / Math.max(input.width, input.height)); if (scale < 1) input = resizeCanvas(input, Math.round(input.width * scale), Math.round(input.height * scale)); } const result = kind === 'remove' ? await removeBackground(input, t => { $('busyText').textContent = t; }) : await aiUpscale(input, t => { $('busyText').textContent = t; }); commit(); setImageData(result.getContext('2d').getImageData(0, 0, result.width, result.height), kind === 'remove' ? 'AI BG REMOVED' : 'AI UPSCALED 4×'); toast(kind === 'remove' ? 'FONDO ELIMINADO CON IA' : 'SUPER-RESOLUCIÓN IA APLICADA'); } catch (e) { console.error(e); toast('IA NO DISPONIBLE · ' + (e?.message || 'REVISA CONEXIÓN / MEMORIA')); } finally { busy(false); } }

async function doVector() { if (!requireImage() || processing) return; finishAdjust(); busy(true, 'VECTORIZANDO', 'Cargando trazador SVG…'); try { const maxSide = 900, scale = Math.min(1, maxSide / Math.max(canvas.width, canvas.height)), temp = resizeCanvas(canvas, Math.max(1, Math.round(canvas.width * scale)), Math.max(1, Math.round(canvas.height * scale))); lastSvg = await vectorize(temp.getContext('2d').getImageData(0, 0, temp.width, temp.height), 'posterized2'); $('modalContent').innerHTML = `<div class="modal-title">VECTOR / SVG READY</div><div class="svg-preview">${lastSvg}</div><div class="modal-actions"><button id="modalSvgDownload">DESCARGAR SVG</button></div>`; $('modal').classList.add('open'); $('modalSvgDownload').onclick = () => downloadBlob(new Blob([lastSvg], { type: 'image/svg+xml' }), `${originalName}-vector.svg`); toast('SVG VECTORIAL GENERADO'); } catch (e) { console.error(e); toast('VECTORIZADOR NO DISPONIBLE · ' + (e?.message || '')); } finally { busy(false); } }
function channels() { if (!requireImage()) return; const im = currentData(), names = ['R', 'G', 'B'], cards = names.map((name, ci) => { const c = document.createElement('canvas'); c.width = im.width; c.height = im.height; const x = c.getContext('2d'), o = x.createImageData(c.width, c.height); for (let i = 0; i < im.data.length; i += 4) { const v = im.data[i + ci]; o.data[i] = o.data[i + 1] = o.data[i + 2] = v; o.data[i + 3] = 255; } x.putImageData(o, 0, 0); return { name, canvas: c }; }); $('modalContent').innerHTML = `<div class="modal-title">DESCOMPONER / RGB</div><div class="channel-grid">${cards.map((c, i) => `<div class="channel-card"><span>CANAL ${c.name}</span><div id="ch${i}"></div><button data-ch="${i}">DESCARGAR PNG</button></div>`).join('')}</div>`; $('modal').classList.add('open'); cards.forEach((c, i) => $('ch' + i).appendChild(c.canvas)); $('modalContent').querySelectorAll('[data-ch]').forEach(b => b.onclick = () => cards[+b.dataset.ch].canvas.toBlob(blob => downloadBlob(blob, `${originalName}-${cards[+b.dataset.ch].name}.png`), 'image/png')); }
function applyHalf() { if (!requireImage() || processing) return; finishAdjust(); commit(); busy(true, 'SEMITONO', 'Generando trama…'); requestAnimationFrame(() => { const out = applyHalftone(canvas, half); setImageData(out.getContext('2d').getImageData(0, 0, out.width, out.height), 'HALFTONE'); busy(false); toast('SEMITONO APLICADO'); }); }
function updatePrint() { const cm = +$('printWidth').value || 30, cmh = +$('printHeight').value || 30, dpi = +$('dpi').value || 300, w = Math.round(cm / 2.54 * dpi), h = Math.round(cmh / 2.54 * dpi); $('printResolution').textContent = `${w} × ${h} PX`; if (!canvas.width) { $('printStatus').textContent = '—'; $('printStatus').className = ''; $('printMeter').style.width = '0'; return; } const ratio = Math.min(canvas.width / w, canvas.height / h), ok = ratio >= 1; $('printStatus').textContent = ok ? 'RESOLUCIÓN ADECUADA' : `FALTAN ${Math.max(1, Math.round((1 - ratio) * 100))}% DE RESOLUCIÓN`; $('printStatus').className = ok ? 'ok' : 'bad'; $('printMeter').style.width = Math.min(100, Math.round(ratio * 100)) + '%'; }
async function downloadPng() { if (!requireImage()) return; try { downloadBlob(await canvasToBlob(canvas), `${originalName}-SZAS.png`); } catch (e) { toast('NO SE PUDO EXPORTAR PNG'); } }
function compare() { if (!requireImage()) return; compareOn = !compareOn; if (compareOn) { compareCanvas.width = canvas.width; compareCanvas.height = canvas.height; compareCtx.putImageData(originalData, 0, 0); compareCanvas.style.display = 'block'; } else compareCanvas.style.display = 'none'; toast(compareOn ? 'ORIGINAL MOSTRADO' : 'COMPARACIÓN CERRADA'); }

function adoptBootImage(e) { const { file, imageData } = e.detail; originalData = cloneImageData(imageData); originalName = (file.name || 'SZAS').replace(/\.[^.]+$/, ''); history.clear(); settings = { brightness: 0, contrast: 0, saturation: 0, sharpness: 0 }; syncSliders(); setImageData(cloneImageData(originalData), 'ORIGINAL', false); $('fileName').textContent = (file.name || 'IMAGEN').toUpperCase(); $('fileHealth').textContent = $('fileHealth').textContent || 'CARGADA'; $('fileHealth').className = 'file-health ok'; updatePrint(); }
window.addEventListener('szas:image-loaded', e => adoptBootImage(e));
if (window.__SZAS_LAST_FILE) adoptBootImage({detail: window.__SZAS_LAST_FILE});

document.querySelectorAll('[data-action]').forEach(b => b.addEventListener('click', () => { const a = b.dataset.action; if (a === 'aiRemove') runAI('remove'); else if (a === 'aiUpscale') runAI('upscale'); else if (a === 'enhance') enhance(); else if (a === 'denoise') denoise(); else if (a === 'vectorize') doVector(); else if (a === 'channels') channels(); else if (a === 'cutout') cutout(); else if (a === 'autocrop') autocrop(); else if (a === 'edgeClean') edgeClean(); else if (a === 'grayscale' || a === 'threshold' || a === 'invert') simple(a); else if (a === 'reset') resetOriginal(); }));
['brightness', 'contrast', 'saturation', 'sharpness'].forEach(k => { $(k).addEventListener('pointerdown', () => { if (requireImage() && !adjustBase) adjustBase = currentData(); }); $(k).addEventListener('input', e => { if (!adjustBase || processing) return; settings[k] = +e.target.value; $(k + 'Out').textContent = e.target.value; renderAdjustments(adjustBase); }); $(k).addEventListener('change', () => finishAdjust()); });
$('zoomIn').onclick = () => { zoom = Math.min(4, zoom * 1.25); canvas.style.transform = `scale(${zoom})`; $('zoomLabel').textContent = Math.round(zoom * 100) + '%'; };
$('zoomOut').onclick = () => { zoom = Math.max(.25, zoom / 1.25); canvas.style.transform = `scale(${zoom})`; $('zoomLabel').textContent = Math.round(zoom * 100) + '%'; };
$('fit').onclick = fit; $('compare').onclick = compare;
$('undo').onclick = () => { if (!canvas.width) return; finishAdjust(); const out = history.undo(currentData()); if (out) { setImageData(out, 'UNDO'); toast('DESHECHO'); } else toast('NO HAY MÁS CAMBIOS'); };
$('redo').onclick = () => { if (!canvas.width) return; finishAdjust(); const out = history.redo(currentData()); if (out) { setImageData(out, 'REDO'); toast('REHECHO'); } else toast('NO HAY MÁS CAMBIOS'); };
document.querySelectorAll('[data-jump]').forEach(b => b.addEventListener('click', () => document.getElementById(b.dataset.jump)?.scrollIntoView({ behavior: 'smooth', block: 'start' })));
$('applyHalftone').onclick = applyHalf;
$('halfInvert').onclick = () => { half.invert = !half.invert; $('halfInvert').querySelector('b').textContent = half.invert ? 'SÍ' : 'NO'; };
$('dotSize').oninput = e => { half.dot = +e.target.value; $('dotOut').textContent = e.target.value; };
$('halfContrast').oninput = e => { half.contrast = +e.target.value; $('halfContrastOut').textContent = e.target.value; };
$('density').oninput = e => { half.density = +e.target.value; $('densityOut').textContent = e.target.value; };
$('angle').oninput = e => { half.angle = +e.target.value; $('angleOut').textContent = e.target.value + '°'; };
$('pattern').onchange = e => half.pattern = e.target.value;
document.querySelectorAll('[data-preset]').forEach(b => b.addEventListener('click', () => { const v = { dark: [5, 75, 100, 45, 'circle'], photo: [4, 45, 95, 45, 'circle'], high: [3, 88, 100, 45, 'square'], mono: [6, 95, 90, 0, 'circle'] }[b.dataset.preset]; [half.dot, half.contrast, half.density, half.angle, half.pattern] = v; $('dotSize').value = v[0]; $('halfContrast').value = v[1]; $('density').value = v[2]; $('angle').value = v[3]; $('pattern').value = v[4]; $('dotOut').textContent = v[0]; $('halfContrastOut').textContent = v[1]; $('densityOut').textContent = v[2]; $('angleOut').textContent = v[3] + '°'; toast('PRESET ' + b.dataset.preset.toUpperCase()); }));
$('printWidth').oninput = updatePrint; $('printHeight').oninput = updatePrint; $('dpi').onchange = updatePrint;
$('dtfPreset').onchange = e => { const p = e.target.value; if (p === 'photo') half = { ...half, dot: 4, contrast: 45, density: 95 }; if (p === 'dark') half = { ...half, dot: 5, contrast: 80, density: 100 }; if (p === 'line') half = { ...half, dot: 3, contrast: 95, density: 100 }; if (p === 'standard') half = { ...half, dot: 6, contrast: 55, density: 100 }; $('dotSize').value = half.dot; $('halfContrast').value = half.contrast; $('density').value = half.density; toast('PRESET DE IMPRESIÓN APLICADO'); };
$('downloadPng').onclick = downloadPng; $('downloadSvg').onclick = () => { if (!lastSvg) return toast('GENERA UN SVG PRIMERO'); downloadBlob(new Blob([lastSvg], { type: 'image/svg+xml' }), `${originalName}-SZAS.svg`); };
$('modalClose').onclick = () => $('modal').classList.remove('open'); $('modal').addEventListener('click', e => { if (e.target === $('modal')) $('modal').classList.remove('open'); });

document.body.dataset.appReady = 'true'; updatePrint();
